### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by ViniFreiri** [lais-tiemi/instagram_html#1]
Cria um branch novo com esse nome: "gh-pages" e puxa o código pra lá, dai o seu site vai ser hospedado como uma página web.

**Comment by lais-tiemi** [comment]
Obrigada pela dica!
https://lais-tiemi.github.io/instagram_html/index.html

**Comment by ViniFreiri** [comment]
Ficou muito bacana sua pagina. Seu Pug é muito fofinho kkkk
